spring:
  application:
    name: order-server

  config:
    import: configserver:http://localhost:8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

resilience4j:
  retry:
    instances:
      payment-service:
        maxAttempts: 3
        waitDuration: 2s

  circuitbreaker:
    instances:
      payment-service:
        slidingWindowSize: 5
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2
        automaticTransitionFromOpenToHalfOpenEnabled: true

  timelimiter:
      instances:
        payment-service:
          timeoutDuration: 1s

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always